// Generated by gencpp from file tensorrt_yolo/InferResult.msg
// DO NOT EDIT!


#ifndef TENSORRT_YOLO_MESSAGE_INFERRESULT_H
#define TENSORRT_YOLO_MESSAGE_INFERRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <KeyPoint.h>

namespace tensorrt_yolo
{
template <class ContainerAllocator>
struct InferResult_
{
  typedef InferResult_<ContainerAllocator> Type;

  InferResult_()
    : bbox()
    , conf(0.0)
    , classId(0)
    , coordinate()
    , Id(0)
    , kpts()
    , vKpts()  {
      bbox.assign(0.0);

      coordinate.assign(0.0);
  }
  InferResult_(const ContainerAllocator& _alloc)
    : bbox()
    , conf(0.0)
    , classId(0)
    , coordinate()
    , Id(0)
    , kpts(_alloc)
    , vKpts(_alloc)  {
  (void)_alloc;
      bbox.assign(0.0);

      coordinate.assign(0.0);
  }



   typedef boost::array<float, 4>  _bbox_type;
  _bbox_type bbox;

   typedef float _conf_type;
  _conf_type conf;

   typedef int32_t _classId_type;
  _classId_type classId;

   typedef boost::array<float, 3>  _coordinate_type;
  _coordinate_type coordinate;

   typedef int32_t _Id_type;
  _Id_type Id;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _kpts_type;
  _kpts_type kpts;

   typedef std::vector< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> >> _vKpts_type;
  _vKpts_type vKpts;





  typedef boost::shared_ptr< ::tensorrt_yolo::InferResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tensorrt_yolo::InferResult_<ContainerAllocator> const> ConstPtr;

}; // struct InferResult_

typedef ::tensorrt_yolo::InferResult_<std::allocator<void> > InferResult;

typedef boost::shared_ptr< ::tensorrt_yolo::InferResult > InferResultPtr;
typedef boost::shared_ptr< ::tensorrt_yolo::InferResult const> InferResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tensorrt_yolo::InferResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tensorrt_yolo::InferResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tensorrt_yolo::InferResult_<ContainerAllocator1> & lhs, const ::tensorrt_yolo::InferResult_<ContainerAllocator2> & rhs)
{
  return lhs.bbox == rhs.bbox &&
    lhs.conf == rhs.conf &&
    lhs.classId == rhs.classId &&
    lhs.coordinate == rhs.coordinate &&
    lhs.Id == rhs.Id &&
    lhs.kpts == rhs.kpts &&
    lhs.vKpts == rhs.vKpts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tensorrt_yolo::InferResult_<ContainerAllocator1> & lhs, const ::tensorrt_yolo::InferResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tensorrt_yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tensorrt_yolo::InferResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tensorrt_yolo::InferResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensorrt_yolo::InferResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensorrt_yolo::InferResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensorrt_yolo::InferResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensorrt_yolo::InferResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tensorrt_yolo::InferResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "504187e05ee572cbf676fa4ca72a57a9";
  }

  static const char* value(const ::tensorrt_yolo::InferResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x504187e05ee572cbULL;
  static const uint64_t static_value2 = 0xf676fa4ca72a57a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::tensorrt_yolo::InferResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tensorrt_yolo/InferResult";
  }

  static const char* value(const ::tensorrt_yolo::InferResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tensorrt_yolo::InferResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4] bbox\n"
"float32 conf\n"
"int32 classId\n"
"float32[3] coordinate\n"
"int32 Id\n"
"float32[] kpts\n"
"KeyPoint[] vKpts\n"
"\n"
"================================================================================\n"
"MSG: tensorrt_yolo/KeyPoint\n"
"float32 x        # x coordinate\n"
"float32 y        # y coordinate\n"
"float32 visible  # visibility (0 or 1)\n"
;
  }

  static const char* value(const ::tensorrt_yolo::InferResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tensorrt_yolo::InferResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bbox);
      stream.next(m.conf);
      stream.next(m.classId);
      stream.next(m.coordinate);
      stream.next(m.Id);
      stream.next(m.kpts);
      stream.next(m.vKpts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InferResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tensorrt_yolo::InferResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tensorrt_yolo::InferResult_<ContainerAllocator>& v)
  {
    s << indent << "bbox[]" << std::endl;
    for (size_t i = 0; i < v.bbox.size(); ++i)
    {
      s << indent << "  bbox[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.bbox[i]);
    }
    s << indent << "conf: ";
    Printer<float>::stream(s, indent + "  ", v.conf);
    s << indent << "classId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.classId);
    s << indent << "coordinate[]" << std::endl;
    for (size_t i = 0; i < v.coordinate.size(); ++i)
    {
      s << indent << "  coordinate[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coordinate[i]);
    }
    s << indent << "Id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Id);
    s << indent << "kpts[]" << std::endl;
    for (size_t i = 0; i < v.kpts.size(); ++i)
    {
      s << indent << "  kpts[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kpts[i]);
    }
    s << indent << "vKpts[]" << std::endl;
    for (size_t i = 0; i < v.vKpts.size(); ++i)
    {
      s << indent << "  vKpts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.vKpts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TENSORRT_YOLO_MESSAGE_INFERRESULT_H
