// Generated by gencpp from file tensorrt_yolo/KeyPoint.msg
// DO NOT EDIT!


#ifndef TENSORRT_YOLO_MESSAGE_KEYPOINT_H
#define TENSORRT_YOLO_MESSAGE_KEYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tensorrt_yolo
{
template <class ContainerAllocator>
struct KeyPoint_
{
  typedef KeyPoint_<ContainerAllocator> Type;

  KeyPoint_()
    : x(0.0)
    , y(0.0)
    , visible(0.0)  {
    }
  KeyPoint_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , visible(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _visible_type;
  _visible_type visible;





  typedef boost::shared_ptr< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> const> ConstPtr;

}; // struct KeyPoint_

typedef ::tensorrt_yolo::KeyPoint_<std::allocator<void> > KeyPoint;

typedef boost::shared_ptr< ::tensorrt_yolo::KeyPoint > KeyPointPtr;
typedef boost::shared_ptr< ::tensorrt_yolo::KeyPoint const> KeyPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tensorrt_yolo::KeyPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tensorrt_yolo::KeyPoint_<ContainerAllocator1> & lhs, const ::tensorrt_yolo::KeyPoint_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.visible == rhs.visible;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tensorrt_yolo::KeyPoint_<ContainerAllocator1> & lhs, const ::tensorrt_yolo::KeyPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tensorrt_yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59b003473f18a0149d9fd800567b8e2d";
  }

  static const char* value(const ::tensorrt_yolo::KeyPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59b003473f18a014ULL;
  static const uint64_t static_value2 = 0x9d9fd800567b8e2dULL;
};

template<class ContainerAllocator>
struct DataType< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tensorrt_yolo/KeyPoint";
  }

  static const char* value(const ::tensorrt_yolo::KeyPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x        # x coordinate\n"
"float32 y        # y coordinate\n"
"float32 visible  # visibility (0 or 1)\n"
;
  }

  static const char* value(const ::tensorrt_yolo::KeyPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.visible);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tensorrt_yolo::KeyPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tensorrt_yolo::KeyPoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "visible: ";
    Printer<float>::stream(s, indent + "  ", v.visible);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TENSORRT_YOLO_MESSAGE_KEYPOINT_H
